# Generated by Django 6.0.2 on 2026-05-12 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_mensaje_pedido_lineapedido_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('plazas_totales', models.PositiveIntegerField(default=20)),
                ('plazas_disponibles', models.PositiveIntegerField(default=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/eventos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '7. Evento',
                'verbose_name_plural': '7. Eventos',
                'db_table': 'eventos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('num_personas', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones', to='menu.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='menu.evento')),
            ],
            options={
                'verbose_name': '8. Inscripción Evento',
                'verbose_name_plural': '8. Inscripciones Eventos',
                'db_table': 'inscripciones_eventos',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
    ]
