# Generated by Django 6.0.2 on 2026-05-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_suscriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email Cliente'),
        ),
    ]
