# Generated by Django 6.0.2 on 2026-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del plato')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug único')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('categoria', models.CharField(choices=[('entrante', 'Entrante'), ('principal', 'Plato Principal'), ('postre', 'Postre'), ('bebida', 'Bebida')], max_length=20, verbose_name='Categoría')),
                ('temporada', models.CharField(choices=[('primavera', 'Primavera'), ('verano', 'Verano'), ('otono', 'Otoño'), ('invierno', 'Invierno'), ('anual', 'Todo el año')], default='anual', max_length=20, verbose_name='Temporada')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/productos/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Disponible para pedir?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': '1. Producto',
                'verbose_name_plural': '1. Productos',
                'db_table': 'productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
