# Generated by Django 6.0.2 on 2026-02-19 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_cliente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='menu.cliente')),
            ],
            options={
                'verbose_name': '3. Carrito',
                'verbose_name_plural': '3. Carritos',
                'db_table': 'carritos',
            },
        ),
        migrations.CreateModel(
            name='LineaCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='menu.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
            options={
                'verbose_name': '3. Lineas de Carrito',
                'verbose_name_plural': '3. Lineas Carrito',
                'db_table': 'lineas_carrito',
                'unique_together': {('carrito', 'producto')},
            },
        ),
    ]
