# Generated by Django 6.0.2 on 2026-02-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_carrito_lineacarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
