# Generated by Django 6.0.2 on 2026-02-05 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellido Cliente')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Cliente')),
                ('edad', models.IntegerField(help_text='Debe ser mayor que 18', validators=[django.core.validators.MinValueValidator(18)], verbose_name='Edad')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug Cliente')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion Cliente')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '3. Cliente',
                'verbose_name_plural': '3. Clientes',
                'db_table': 'clientes',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
    ]
