# Generated by Django 6.0.2 on 2026-02-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellidos', 'nombre'], 'verbose_name': '2. Cliente', 'verbose_name_plural': '2. Clientes'},
        ),
    ]
