# Generated by Django 6.0.2 on 2026-05-11 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_cliente_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondido', 'Respondido')], default='pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='menu.cliente')),
            ],
            options={
                'verbose_name': '6. Mensaje',
                'verbose_name_plural': '6. Mensajes',
                'db_table': 'mensajes',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=100)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('tipo_entrega', models.CharField(choices=[('domicilio', 'Envío a domicilio'), ('recogida', 'Recogida en tienda')], default='domicilio', max_length=20)),
                ('direccion_entrega', models.CharField(blank=True, max_length=200, null=True)),
                ('metodo_pago', models.CharField(choices=[('paypal', 'PayPal'), ('tarjeta', 'Tarjeta de crédito')], default='paypal', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('preparando', 'En preparación'), ('listo', 'Listo para envío/recogida'), ('enviado', 'En reparto'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='menu.cliente')),
            ],
            options={
                'verbose_name': '5. Pedido',
                'verbose_name_plural': '5. Pedidos',
                'db_table': 'pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='menu.pedido')),
            ],
            options={
                'verbose_name': '5. Línea de Pedido',
                'verbose_name_plural': '5. Líneas de Pedido',
                'db_table': 'lineas_pedido',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=100)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('num_personas', models.PositiveIntegerField(default=2)),
                ('sala', models.CharField(choices=[('principal', 'Sala principal'), ('terraza', 'Terraza interior')], default='principal', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='menu.cliente')),
            ],
            options={
                'verbose_name': '4. Reserva',
                'verbose_name_plural': '4. Reservas',
                'db_table': 'reservas',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
