# Generated by Django 6.0.2 on 2026-05-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_evento_inscripcionevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/productores/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '9. Productor',
                'verbose_name_plural': '9. Productores',
                'db_table': 'productores',
                'ordering': ['nombre'],
            },
        ),
    ]
