# Generated by Django 6.0.2 on 2026-05-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_productor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '10. Suscriptor',
                'verbose_name_plural': '10. Suscriptores',
                'db_table': 'suscriptores',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
